import React, { useCallback, useMemo } from "react";

type Props = {};
// generated by chat-gpt
const indianNames = [
	"Rohit Kumar",
	"Anjali Deshpande",
	"Akash Singhania",
	"Nisha Garg",
	"Deepak Saini",
	"Rajesh Sharma",
	"Sanjay Patil",
	"Vikas Agarwal",
	"Kamal Bhatia",
	"Anuradha Rana",
	"Ankit Dube",
	"Divya Sethi",
	"Priya Mehta",
	"Manish Khanna",
	"Shruti Nair",
	"Ashok Joshi",
	"Swati Iyer",
	"Nikhil Balaji",
	"Ruchi Choudhary",
	"Rajeev Bhandari",
	"Aruna Mahajan",
	"Sushant Pawar",
	"Yogesh Singh",
	"Aparna Chakraborty",
	"Abhishek Nair",
	"Amitabh Gupta",
	"Smita Singhania",
	"Suresh Patel",
	"Geetika Reddy",
	"Pooja Rathore",
	"Ravi Menon",
	"Nikhita Malhotra",
	"Prashant Suri",
	"Shikha Saxena",
	"Vivek Chakrabarty",
	"Sonal Gupta",
	"Vishal Patel",
	"Aditi Shukla",
	"Aman Singh",
	"Anisha Kapoor",
	"Abhilash Nambiar",
	"Arvind Iyer",
	"Kavita Venkataraman",
	"Abhishek Sengupta",
	"Rajeev Garg",
	"Asha Bhatt",
	"Pranav Singhania",
	"Deepali Varma",
	"Sneha Shah",
	"Abhay Chauhan",
];
export function randomNumber(min: number, max: number) {
	return Math.floor(Math.random() * (max - min + 1) + min);
}
function useRandomName() {
	const randomName = useCallback(() => {
		return indianNames[randomNumber(0, 49)];
	}, [indianNames]);
	return useMemo(randomName, []);
}

export default useRandomName;
